openapi: 3.0.3
info:
  title: OarChat API
  version: 1.0.0
  description: REST endpoints for OarChat socket server (health check and test routes)
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /:
    get:
      summary: Test HTTP route
      operationId: getOar
      responses:
        '200':
          description: HTML success response
          content:
            text/html:
              schema:
                type: string
                example: <h1>Socket.IO Server is Running</h1>

  /healthz:
    get:
      summary: Health check
      operationId: getHealthz
      responses:
        '200':
          description: Healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

components: {}
